### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by stefanbuttigieg** [WorldHealthOrganization/godata#12]
When running 01_data_import_api.R in its current format, the access_token variable is not being defined, that is, it stays as 'NULL' despite having correct the right role, username, password, outbreak id and the access token being generated (in the console). 

As a result, I'm unable to pull data from Go.Data through R. The exact error I'm getting is Error 401 - Authorization Required

Currently using RStudio Version 1.3.1093 and R x64 4.0.3

@sarahollis maybe you might help on this one?

**Comment by stefanbuttigieg** [comment]
Following up on this, checked admin logs and found the following errors:

{"level":"error","message":"(node:6072) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.","timestamp":"2020-12-21T20:31:17.999Z"}

{"level":"info","message":"Initializing database connection","timestamp":"2020-12-21T20:33:19.776Z"}

{"level":"info","message":"Database connection initialized","timestamp":"2020-12-21T20:33:19.861Z"}

**Comment by stefanbuttigieg** [comment]
Any update on this please? @sarahollis ?

**Comment by sarahollis** [comment]
Hi @stefanbuttigieg  so sorry that i did not more quickly reply on Github, the fix was outlined over in the Community of Practice: https://community-godata.who.int/conversations/dashboards-and-analysis/http-get-request-problems/5fe465f85514e27f8e0237cc

In line 54, which previously said

`access_token <- content$response$access_token`

you for some reason need to take out "response" so that it only says

`access_token <- content$access_token`

This has already been updated in the 01_data_import_api.R script in repo. Hope it works for you, please let me know!
Sara

**Comment by stefanbuttigieg** [comment]
Comment much appreciated. Will test soon

**Comment by stefanbuttigieg** [comment]
Submitted a Pull Request #27 to update code as you mentioned

**Comment by sarahollis** [comment]
@stefanbuttigieg  this was already edited in the code when the query was addressed on CoP (see here):
https://github.com/WorldHealthOrganization/godata/blob/master/analytics/r-reporting/report_sources/01_data_import_api.R
so no changes needed
