### ISSUE TITLE
Select a Platform for Go.Data Community of Practice

### ISSUE THREAD

**Issue by smbuthia** [WorldHealthOrganization/godata#76]
The Go.Data community of practice is being transitioned out of the previous community platform. The previous community platform provided a space where community members could:

- request for demo accounts,
- ask questions about setting up Go.Data,
- seek technical support for issues,
- receive product updates, and 
- share use cases that they were working on

This transition presents an opportunity to set up a robust community platform with established systems and processes for product updates, collaboration, and technical support.

Some potential options for this include; Notion, Discourse, and Discord.

**Comment by AmyMikhail** [comment]
I'm not familiar with the first two, but I do use Discord for a couple of things.  Discord is app based, which has both advantages and disadvantages.  The advantage is that if you install the app on your phone and on your computer, you get notifications when people reply to a post that you wrote or are following - this does make the communication feel much more instant.  But I have noticed that the desktop discord app is very slow to open, and for some people the extra step of having to install an app as opposed to just bookmarking a url in their browser might prevent them from using it.  Discord does have a web client too, and if going down that option I would recommend having an easy to access link to that on Go.Data web pages so that people who don't want (or are unable) to install the app can still access it.

**Comment by silviaemorreale** [comment]
The Go.Data community of practice (CoP) has transitioned to the [GOARN Knowlege Platform](https://goarn.who.int/virtual-spaces/godataproject). The CoP is a virtual space that brings together Go.Data users worldwide, allowing members to:

- Share best practices, frameworks, and tools.
- Collaborate on open-source projects.
- Engage in discussions and peer learning.
- Contribute to knowledge sharing through publications, tutorials, and case studies.

To join the Go.Data CoP, interested individuals can easily join by clicking [[here](https://extranet.who.int/dataformv3/index.php/452384?lang=en)] and completing a short form.
